USE [master]
GO

/****** Object:  Database [WordCounterDB]    Script Date: 2021/09/16 12:53:57 ******/
CREATE DATABASE [WordCounterDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WordCounterDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WordCounterDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WordCounterDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WordCounterDB_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WordCounterDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WordCounterDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WordCounterDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WordCounterDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WordCounterDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WordCounterDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WordCounterDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WordCounterDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WordCounterDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WordCounterDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WordCounterDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WordCounterDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WordCounterDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WordCounterDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WordCounterDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WordCounterDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WordCounterDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WordCounterDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WordCounterDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WordCounterDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WordCounterDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WordCounterDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WordCounterDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WordCounterDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WordCounterDB] SET  MULTI_USER 
GO

ALTER DATABASE [WordCounterDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WordCounterDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WordCounterDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WordCounterDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WordCounterDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WordCounterDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WordCounterDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WordCounterDB] SET  READ_WRITE 
GO


